### ISSUE TITLE
Support for deferred/partial responses

### ISSUE THREAD

**Issue by helfer** [apollographql/graphql-server#18]
At some point in the future, apolloServer should support sending multiple partial responses (over a websocket connection for example). This issue is to keep that in mind while we build the first version which will not have such a feature.

**Comment by stubailo** [comment]
The talk about GraphQL future at React Europe tomorrow should help us have somewhat of a spec to follow/collaborate on, I think!

**Comment by helfer** [comment]
Let's wait and see, haha. Curious to see if there will finally be any movement on subscriptions.

**Comment by paralin** [comment]
When do you guys plan to revisit this?

**Comment by helfer** [comment]
Closing this issue since this has moved a bit farther into the future. We already have a PR open that would add a ws transport to support this. Other than that, support needs to be added in the execution engine first, so the best thing we can do on the server is support different execution engines, some of which might return observables from the execute function instead of a promise.
