### ISSUE TITLE
Unexpected condition when using POST without body

### ISSUE THREAD

**Issue by KenanSulayman** [apollographql/graphql-server#206]
When doing a POST request without a body, the apollo-server will invoke graphql and cause an error to be thrown.

This is, because *query* is not defined by the user and the apollo-server only checks for the request type: https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L73.

**Comment by helfer** [comment]
@KenanSulayman yes, you're right! We could definitely use more sanity checking of inputs and better error messages. If you could make a PR, I'd be more than happy to merge it! 🙂

**Comment by helfer** [comment]
I _think_ we throw a better error now.
