### ISSUE TITLE
Encourage runkit use when submitting issues?

### ISSUE THREAD

**Issue by lorensr** [apollographql/graphql-server#218]
Either in CONTRIBUTING.md or in issue template, could link to a basic server template. 

Eg:

https://runkit.com/lorensr/apollo-endpoint-trial/2.0.0

results in the endpoint:

https://runkit.io/lorensr/apollo-endpoint-trial/2.0.0/graphql

(`.io` instead of `.com`, and path added)

**Comment by stubailo** [comment]
Hmm, what's the benefit of this? Is it easier than creating a repo with a reproduction?

**Comment by lorensr** [comment]
Yeah, don't have to clone and npm install, and easier to make and demo
changes, but something new to learn, might not be worth it

**Comment by helfer** [comment]
I'm not sure if this is going to help all that much. Maybe if there was a first example issue I could be convinced otherwise 🙂

**Comment by lorensr** [comment]
#217 was an example, albeit not needed during triage
