### ISSUE TITLE
Graphiql fetcher observable for subscriptions

### ISSUE THREAD

**Issue by rogchap** [apollographql/graphql-server#222]
Currently only uses the fetch API, but would be great to have graphiql's `fetcher` to return an Observable to support testing subscriptions.
Details here: https://github.com/graphql/graphiql/pull/104

Hoping to put a PR together, but want to get this documented in-case someone beats me to it 😄

**Comment by DxCx** [comment]
For which transport? I have it already implemented for websocket...

**Comment by rogchap** [comment]
@DxCx where have you implemented? Would be great to take a look. Couldn't find anything in the source here.

**Comment by DxCx** [comment]
Well i was working to achieve subscriptions using observables on server as well. (Resolvers returns observable, instead of manager)

https://github.com/DxCx/apollo-server/blob/rxjs-with-ws/src/modules/renderGraphiQL.ts#L39

Please note that my transport is full graphql over websocket and not the same as websocket protocol for subscriptions that is used today

**Comment by helfer** [comment]
@rogchap I'm not sure if this issue has anything to do with graphql-server. I think graphiql would be a better place for it, but as far as I know fetch can already return an observable there.

**Comment by rogchap** [comment]
@helfer I think that graphiql is fine and more to do with how we implement `graphQLFetcher`:

https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-module-graphiql/src/renderGraphiQL.ts#L104

Maybe there's more to it?

**Comment by DxCx** [comment]
yes. Graphiql supports observables.
a fetch function that returns observable should be provided.

**Comment by helfer** [comment]
@rogchap indeed, you're right! Looking forward to that PR :wink:

**Comment by laxgoalie392** [comment]
any update on this?

**Comment by DxCx** [comment]
I've started working on a proper websocket interface design (#272).
once this will be supported i'll probably submit my renderGraphiql patch to support Observables over websocket

**Comment by helfer** [comment]
I think @Urigo's solution will do for now.
