### ISSUE TITLE
(regression?) Possible inconsistent behavior with `formatError`

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/graphql-server#235]
Just noticed a possible regression.

If I provide a "no-op" for `formatError` as such:

```
formatError: error => error
```

The response includes the entire error object.

However, if I completely omit `formatError`, the response includes a simple object containing `message`.  This seems weird, like a mistake.  Is this a regression?  I can provide more data if needed, but it's pretty easy to reproduce haha at least for me

**Comment by stubailo** [comment]
Did it do something different before? We've always just used the default `formatError` function from the `graphql` package. In any case I would suggest always explicitly providing one if you care about exactly what fields are on there.

Also, which version are you upgrading from?

**Comment by thebigredgeek** [comment]
Before it looked like it called graphql.formatError BEFORE calling the formatError hook on apollo.  It appeared to pass the result from graphql.formatError as the param to apollo.formatError.
