### ISSUE TITLE
How to cache queries based on URL (e.g. using cloudflare)?

### ISSUE THREAD

**Issue by faceyspacey** [apollographql/graphql-server#245]
Is it possible to configure the middleware to receive request data as URL parameters instead of in the body? 

I'm looking to make use of cloudflare's URL caching for some of my request endpoints, but if the body must be used, it's a non-option.

**Comment by DxCx** [comment]
hi @faceyspacey 
we've introduced GET support on latest version,
so basically you can now send GET requests to the server,
as far as i know, cloudflare's should cache them.
please give it a try and update here ;)

**Comment by Poincare** [comment]
Yup, this is entirely dependent on the type of HTTP request. See the [HTTP 1.1 RFC](https://www.ietf.org/rfc/rfc2616.txt) (specifically Section 13, which describes caching correctness) for more details on when HTTP caches will cache the request.
