### ISSUE TITLE
Serialize a Promise or Observerable for slow resolvers

### ISSUE THREAD

**Issue by linonetwo** [apollographql/graphql-server#259]
I'm experimenting with GraphQL wrapping with Amazon's Mechanical Turk (AMT), which is a human driven knowledge service.

![v2-0ca92ca2db85609046c4cf477fdb6bd7_b](https://cloud.githubusercontent.com/assets/3746270/21609891/e1d42f7e-d1ff-11e6-9328-85b6f57bbee3.jpg)

Look at this ↑ ```HCrowd.prompt``` let us ask five **real** human where is the best place in NewYork. This is gonna be a slow API behind resolver.

So I'm wondering is there any way to serialize a Promise that resolves to a data, to client side? 

Idea:

As https://github.com/apollostack/graphql-server/issues/34 said, GraphQL can update some field asyncly:

Query:

```javascript
{
  feed {
    stories {
      author { name }
      message
      likeCount @live
    }
  }
}
```

Initial payload (like normal):

```json
{
  "feed": {
    "stories": [
      {
        "author": { "name": "Lee Byron" },
        "message": "GraphQL est grand!",
        "likeCount": 5
      },
      {
        "author": { "name": "Dan Schafer" },
        "message": "Anyone for lunch?",
        "likeCount": 5
      },
      {
        "author": { "name": "Christopher Chedeau" },
        "message": "React Native est l'avenir",
        "likeCount": 50
      }
    ]
  }
}
```

Sample update delta:

```json
{
  "path": [ "feed", "stories", 0, "likeCount" ],
  "data": 6
}
```

And maybe we can serialize a Promise by placing a placeholder before data comes in, which looks likes a json-LD annotation:

```json
{
  "feed": {
    "stories": [
      { "@type" : "$Promise<Object>" }
    ]
  }
}
```

Thus letting apollo-client wrap that field into a Promise.

I know apollo-client is based on observable, so this will be a bit complicated. But if you think this is interesting, let's discuss more. And I'm glad to try a PR.

**Comment by DxCx** [comment]
hi @linonetwo are you familiar with @live / @stream directives?
sounds to me that this is what you are looking for (They are not available yet)

**Comment by linonetwo** [comment]
When will these directives become available?
I've heard about them for quite a time.

**Comment by helfer** [comment]
@linonetwo this sounds very much like a corner case. I think for the moment your best bet would be a graphql subscription or maybe polling. Definitely not something I would implement with a single GraphQL request. I'd look at this more as a mutation (eg submitting a job to MT) and then checking the status of that job.

I'm going to close this since it's not really an issue with graphql-server, but feel free to continue the discussion, I think it's a very interesting application! 🙂
