### ISSUE TITLE
Manually run a query

### ISSUE THREAD

**Issue by astanciu** [apollographql/graphql-server#289]
Is there an exposed method of running a query manually? With `graphql-server-express` queries are automatically executed through the request cycle, but sometimes it would be helpful to run GQL queries from within other parts of the app to get a full, joined, object that GQL produces.

**Comment by DxCx** [comment]
hi @astanciu,
eventually, graphql-server is an network wrapper for graphql core function.
if you don't want to use it over network, you can just run it standalone:
```javascript
import { graphql } from 'graphql';
import scheme from './scheme';

const query = `{
  me {
    name
  }
}`;

const result = graphql(scheme, query);
console.log(result);
```

function documentation can be found [here](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L19)

**Comment by astanciu** [comment]
Perfect! Thank you!

**Comment by DxCx** [comment]
you are welcome! :)
