### ISSUE TITLE
Repo & NPM Version mismatch with lagging peer dependency

### ISSUE THREAD

**Issue by mrlannigan** [apollographql/graphql-server#291]
I was installing the graphql-server-hapi@latest (0.5.2) with graphql@0.9.1 and the latest npm version doesn't match the current repo version. I'm specifically looking at the peer dependencies as the npm version doesn't allow ^0.9 graphql.

**Comment by DxCx** [comment]
np about that @mrlannigan 
the fix for that is already merged to master and we are planning on releasing a new version today. ;)

**Comment by marciobueno1** [comment]
Today I installed graphql-server-express and it gave me this error:

graphql-server@0.3.2 requires a peer of graphql@^0.6.1 || ^0.7.0 but none was installed.

The installed graphql version is 0.9.1...

Probably the fix refered by @DxCx  wasn't released yet...

**Comment by DxCx** [comment]
hi @marciobueno1,
the fix was released, however, `graphql-server` is deperecated...
please look at the instructions for the right package name ...

**Comment by NitroBAY** [comment]
npm WARN apollo-server@0.3.3 requires a peer of graphql@^0.6.1 || ^0.7.0 but none was installed.
