### ISSUE TITLE
basic  lambda  starter-kit?

### ISSUE THREAD

**Issue by nfurfaro** [apollographql/graphql-server#298]
Hi, 
I'm trying to use graphql-server-lambda in my serverless framework service. It would be great if there were a simple starter file for a schema.js (and maybe a resolvers.js ) to go with the example graphql.js in the README for graphql-server-lambda. 
I've been trying to piece this together from different sources but am having a hard time getting it to work.

**Comment by soda0289** [comment]
Try this: https://github.com/NeoReyad/graphql-lambda/blob/master/graphql.js

It is very basic but it is what I used to test it.

**Comment by soda0289** [comment]
Check your cloud watch logs for errors. There could be some bugs still or mis-configuration from the template.

**Comment by nfurfaro** [comment]
Thanks! I will give it a go. Can you tell me if graphql-server-lambda
requires something like graphql-server-express with a server.js as well, or
does it work on it’s own?

**Comment by soda0289** [comment]
The graphql-server-lambda package is all you need to run the server in Lambda. There is no dependency on express or graphql-server-express. The API Gateway will take care of HTTP requests and responses for you.

**Comment by nfurfaro** [comment]
Thank you for that.

**Comment by nfurfaro** [comment]
in serverless.yml,  the path for the GraphQLInspector function is /Prod/graphql...
I don't quite understand the "/Prod" part as I'm currently deploying my "dev" stage.
Is it necessary?

**Comment by soda0289** [comment]
When you deploy with the stage name set to 'dev' all the api endpoints of the url will end in /dev/. In my example I used the stage name 'prod'. Not sure why the name started with a capital P. It could be that I used a different template the first time I deployed. 

The GraphQLInspector will submit ajax requests to itself and needs to know the url of the api. This is why I had to set 'endpointURL' to /Prod/ but if your stage is dev you might need to set it to /dev/ or /Dev/.

If you want to check what the url is for the api endpoint check the dashboard of the api in the api gateway.

**Comment by nfurfaro** [comment]
great, thanks for the help.

**Comment by nfurfaro** [comment]
@soda0289
I got it working,  thanks!

**Comment by DxCx** [comment]
@soda0289 would you mind share what was your issue so others can learn in the future?

**Comment by nfurfaro** [comment]
I have not yet got the grapiql GET endpoint to work yet, but am able to use Graphiql with the primary GET endpoint.
 I used the file that @soda0289 posted a link to here 
https://github.com/NeoReyad/graphql-lambda/blob/master/graphql.js
As was mentioned, it includes a very simple starter schema and resolvers, which was just what i was looking for.

**Comment by soda0289** [comment]
I will look into the graphql GET endpoint not working. The problem is that it is not calling the lambda function when query parameters are passed into it. You have to manually add them to the api gateway to have them accepted and passed through. Might have to define a swagger file for deployment to work with cloud formation. Will look into later in the week.

**Comment by nfurfaro** [comment]
Just to be clear: 
The /graphiql (GET) endpoint is not working for me. but the /graphql (GET) endpoint works.
It coiuld easily be something I'm doing wrong though.

**Comment by soda0289** [comment]
Oh. I was having issues with the /graphql GET endpoint, but could be my stack was messed up, but the /graphiql GET endpoint worked fine. Do you know if the lambda function is being called at all? Is it producing the html?

**Comment by nfurfaro** [comment]
i'm not using the graphiql endpoint at all now. Have switched to using https://github.com/bencooling/serverless-plugin-graphiql
for my local development.
