### ISSUE TITLE
graphqlExpress options function mistakes fail silently

### ISSUE THREAD

**Issue by matt-way** [apollographql/graphql-server#303]
If you do something like this,

```
graphqlExpress(req => ({
  schema,
  context: {
    someValue: req.user.value // where req.user is undefined
  }
}))
```

any calls to the server fail silently. Client just receives 500.

**Comment by helfer** [comment]
@matt-way The server throws an error here: https://github.com/apollographql/graphql-server/blob/bbe12af4574871836604c1be1320ebab586ccbb4/packages/graphql-server-core/src/runHttpQuery.ts#L37

How you want to deal with that is up to you. You could log it to the console with an express middleware for example.

**Comment by matt-way** [comment]
Sorry, my bad, missed that it wasn't being caught. Thanks for the reply.
