### ISSUE TITLE
error: "Cannot POST /undefined?" on graphql interface

### ISSUE THREAD

**Issue by lnmunhoz** [apollographql/graphql-server#304]
I followed all the steps on the tutorials but cannot understand why my graphql interface is giving the error `Cannot POST /undefined?`.

I created a simple repository to showing the bug https://github.com/lnmunhoz/graphql-server-issue-304.

**Comment by DxCx** [comment]
my guessing will be
https://github.com/lnmunhoz/graphql-server-issue-304/blob/master/index.js#L10
note that it should be `endpointURL`.
you couldn't know that if you would've used typescript instead of plain javascript ;)

**Comment by lnmunhoz** [comment]
@DxCx Thank you!
