### ISSUE TITLE
Should the HAPI route also be specifying OPTIONS as a valid method?

### ISSUE THREAD

**Issue by bryanerayner** [apollographql/graphql-server#310]
I have been running into an error with HAPI and CORS.

https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-hapi/src/hapiApollo.ts#L59

Should OPTIONS also be specified here? Apollo client makes an OPTIONS request and I am continuing to receive 400 errors when attempting to do mutations. Queries work fine however.

Thanks

**Comment by helfer** [comment]
@bryanerayner I believe you need to turn on cors. See the docs here: https://hapijs.com/api/3.0.0#server-options

**Comment by christophercliff** [comment]
Hapi appears to have removed the server level `cors` config. In v16 it only exists at the route level. Any tips on configuring?

**Comment by christophercliff** [comment]
Figured it out. The plugin accepts `route` options, e.g.

```js
server.register({
  register: graphqlHapi,
  options: {
    path: '/graphql',
    route: { cors: true },
    graphqlOptions: { schema: myGraphQLSchema },
  },
})
```
