### ISSUE TITLE
Creating a generic filter argument

### ISSUE THREAD

**Issue by thisbejim** [apollographql/graphql-server#312]
How might you implement filters with graphql-server in a way that is similar to how [Graphcool does it](https://www.graph.cool/docs/reference/simple-api/filtering-by-field-xookaexai0)?

For example, if you want to perform a filter like this:
```
filter: {
  name: 'John'
}
```

How might I define a generic filter type that can be used across queries that accepts an arbitrary number of properties that can each be of [any value](http://graphql.org/graphql-js/type/#graphqlinputobjecttype), e.g `[fieldName: string]: Any`?

You can go ahead and do this explicitly e.g:

```
input PersonFilter {
  name: String
}
```

(^ This might actually be how graphcool does it, they may just generate it automatically)

But I'm wondering if you can create just one type for this.

Cheers :)

**Comment by stubailo** [comment]
Yeah I bet Graphcool is just generating a filter input type for everything separately. I wouldn't really suggest doing this in a hand coded API so that you can optimize specific filters that you know you are going to use.

**Comment by thisbejim** [comment]
Awesome thanks @stubailo 👍
