### ISSUE TITLE
How to return an array of errors from a mutation?

### ISSUE THREAD

**Issue by ryancole** [apollographql/graphql-server#317]
It looks like the response payload for a failed mutation (or query) contains an array of errors. I assume it supports more than one error in a single response. I can't figure out how to return an array of errors from my mutation resolver, though. I've tried returning an array of literal `Error` instances, but that doesn't seem to work.

Is this possible?

**Comment by helfer** [comment]
No, it's not possible. Each resolver can only throw one error. The reason errors is an array is that multiple resolvers may throw errors during the execution of a single query. You could either return a custom error in your case, or you can make the error part of the return type by using a union (i.e. returning either the result, or an error inside the `data` field).

**Comment by gastonmorixe** [comment]
@helfer why is it not possible or wrong to return an array of errors? is a 1-1 match between resolvers-errors part of the spec? thank you

**Comment by glasser** [comment]
The GraphQL spec does allow for multiple errors from the same path, but I don't believe this is currently supported by the execution model used here. You can throw an error with an `extensions` field on it containing whatever details you want (such as more errors), or encode the complex error handling directly into your schema as @helfer suggested.

**Comment by gastonmorixe** [comment]
@glasser Yeah, I understand we can customize with extensions but unless this is part of the GQL spec I don't understand why forcing developers to return this nested and not allow any way to customize the output of the errors even in the formatter. Maybe I am missing something. In the other thread I've provided the lines why this happens.

**Comment by rwilliams3088** [comment]
+1 Need to be able to have multiple errors reported
