### ISSUE TITLE
Support for micro as a server

### ISSUE THREAD

**Issue by tonyxiao** [apollographql/graphql-server#324]
https://github.com/zeit/micro

GraphQL is just a single endpoint, which makes it super nice to just support micro as server option.

**Comment by nnance** [comment]
@tonyxiao @helfer I plan to have a PR for this shortly.  I have this already built just need to merge it some recent changes to master

**Comment by stubailo** [comment]
Awesome!

**Comment by thebigredgeek** [comment]
Woot!  I am happy about this.  Can we get this merged ASAP?  I am writing a piece of content RIGHT NOW and would like to use Micro for it
