### ISSUE TITLE
Why stripping out non enumerable properties from the context when batching?

### ISSUE THREAD

**Issue by fabiospampinato** [apollographql/graphql-server#326]
Using [Passport](http://passportjs.org), I wanted to implement a `login` mutation. Passport adds a `login` function to the `req` object, so I thought that using the `req` object as the context of my resolvers should be enough for having access to it from the mutation.

Unfortunately I tried to access `context.login` from the mutation and I got `undefined`.

Surprised enough I dag into `graphql-server-core` and I found the following inside `runHttpQuery.js`:

```javascript
if (isBatch) {
  context_1 = Object.assign({}, context_1 || {});
}
```

Which, if I understand it properly, has the only function of removing all the non enumerable properties from the context.

Since the way Passport adds its extra properties to the `req` object makes them non enumerable, I coudn't access them anymore.

Why are we doing this? Why only if batching?

**Comment by DxCx** [comment]
Hey @fabiospampinato,
The true intention of this line is to duplicate the original context given, so if one of the resolvers changes it it wont hold.
Please try to pass req as a member of context and not context itself :)

**Comment by fabiospampinato** [comment]
Being a shallow copy it doesn't really prevent a resolver from mutating it, and doing a deep copy is probably too expensive, perhaps just discouraging developers from mutating it would be enough.

Thanks you.

**Comment by DxCx** [comment]
well, yes, you are right, the resolver can modify the inner keys and we are fine with that.
the intention is not to pass the user object as is so the context itself won't be modified.
