### ISSUE TITLE
Need to fix Koa integration tests on Node v4

### ISSUE THREAD

**Issue by DxCx** [apollographql/graphql-server#329]
KoA integration tests are broken on node 4. seems like koa uses es6 features.
we need to dig deeper to understand what was changed exactly, and make sure that the latest supported koa for node 4 i supported by us as well.

Temporary W/A which just disables Koa tests on node v4: #328

**Comment by DxCx** [comment]
from koa's offical github: `Koa requires node v7.6.0 or higher for ES2015 and async function support.`
do we want to split packages for koa 1 & koa 2?
koa 2 removed support for node 4&6.
if not we should just disable testings for node 4&6.

**Comment by DxCx** [comment]
@helfer

**Comment by soda0289** [comment]
We could use babel with babel-register to compile the code on the fly before execution. Koa mentions this in the README:
https://github.com/koajs/koa#babel-setup

**Comment by DxCx** [comment]
as much as i know apollo doesn't want to use babel,
they want the code to be supported by node 4+ as is.
we already had failing releases because testing was done using node 4 =\

**Comment by helfer** [comment]
This is indeed a little bit annoying. I think the best path forward is as @DxCx suggested: disable Koa tests on node 4 and support only Koa 2 going forward.

**Comment by DxCx** [comment]
Yeah im sorry that was node 7..
You need both async and es2015

**Comment by DxCx** [comment]
@helfer do we want to remove support from KOA on both Node 4 and 6 or split packages for KOA1 and KOA2?

**Comment by helfer** [comment]
@DxCx I'd be happy to remove Koa support for Node 4 and 6 going forward. I don't think it makes sense for us to put in the work if neither of us are using it. If someone who is using Koa comes forward and wants to maintain that part and make separate versions for Koa 1 and 2, we can still do that.
