### ISSUE TITLE
Make graphql-server-core runHttpQuery output formatter configurable

### ISSUE THREAD

**Issue by gajus** [apollographql/graphql-server#331]
I want to format JSON to the browser, i.e. I need to modify the JSON thats being sent to the browser (not the object itself, but an actual JSON thats being sent to the browser).

Specifically, I want to use https://github.com/kawanet/msgpack-lite to communicate between client and the server.

How do I intercept the response logic?

**Comment by gajus** [comment]
Looking at the [source code of `graphql-server-express`](https://github.com/apollographql/graphql-server/blob/37ae74c5fefe6032838d4afed6d7dc4018055d06/packages/graphql-server-express/src/expressApollo.ts#L19-L54), it appears I don't need to use it at all, and I should simply be using `runHttpQuery` from `graphql-server-core`.

**Comment by gajus** [comment]
Looks like this behaviour is hardcoded into `graphql-server-core`.

https://github.com/apollographql/graphql-server/blob/37ae74c5fefe6032838d4afed6d7dc4018055d06/packages/graphql-server-core/src/runHttpQuery.ts#L153

**Comment by soda0289** [comment]
I think msgpack can encode strings they have an example on the README for command line that does this.

**Comment by helfer** [comment]
@gajus I know it's been a while, but I think it's still worth asking: is what you want essentially to be able to provide a custom serialization function?

**Comment by gajus** [comment]
> is what you want essentially to be able to provide a custom serialization function?

I have done that by adding a postprocessor of the response, i.e. decoding the generated JSON and re-serializing as needed.

**Comment by gajus** [comment]
I'd close this issue as non-priority as there are simple workarounds.

**Comment by helfer** [comment]
Ok, thanks!
