### ISSUE TITLE
Cannot use graphQL server with express router

### ISSUE THREAD

**Issue by hckhanh** [apollographql/graphql-server#336]
I have a demonstration like this:

```
const express = require('express')
const router = express.Router()
const { graphqlExpress, graphiqlExpress } = require('graphql-server-express')
const schema = require('./schema')
const bodyParser = require('body-parser')

router.use('/graphql', graphqlExpress({
  schema: schema,
  debug: true
}))

router.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql'
}))

module.exports = router
```

When I try to move the server from **app** to **router**. It cannot run correctly. I means I move the api from **/graphql** to **/api/graphql** using router in express. It's return 404 code.

**Comment by helfer** [comment]
@hckhanh Apollo Server is just a normal Express middleware. I think this is more likely to be an issue with your setup or with Router.

**Comment by hckhanh** [comment]
I think my implementation is fine. When I use express-graphql in my router, it runs smoothly.

**Comment by hckhanh** [comment]
Now I am find out my mistake. The endpointURL is not correctly 🗡 
It should be:

```
router.use('/graphiql', graphiqlExpress({
  endpointURL: '/api/graphql'
}))
```

Apologize for my bad 😢

**Comment by ahelord** [comment]
`const { ApolloServer, gql } = require('apollo-server-express');

const server = new ApolloServer({
    schema: schema,
    introspection: true
}); 

server.applyMiddleware({ app:router });

module.exports = router;`
