### ISSUE TITLE
Use debug for logging

### ISSUE THREAD

**Issue by gajus** [apollographql/graphql-server#338]
Avoid defining custom log handlers, e.g. https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-core/src/runQuery.ts#L65

There are purpose built libraries that enable better DX by unifying the logging experience, e.g. https://www.npmjs.com/package/debug

**Comment by stubailo** [comment]
Paging @thebigredgeek!

**Comment by thebigredgeek** [comment]
Yeah I think this might be worthwhile.  It's what every other lib seems to use in Node haha

**Comment by stubailo** [comment]
Migrating this to `debug` seems reasonable to me!

**Comment by thebigredgeek** [comment]
@stubailo we might also want to consider using debug in `apollo-client` for log and error output

**Comment by helfer** [comment]
Happy to accept a PR that changes this, but if nothing materializes I will close the issue as it's not an issue per se but more of a feature request.

**Comment by gajus** [comment]
I am no longer advocating for debug. I've had to hard-replace debug module for all dependencies (`rm -fr ./node_modules/debug && mv ./node_modules/our-debug ./node_modules/debug`) when going into production, because debug output is non-parsable.

See this issue for reference https://github.com/visionmedia/debug/issues/442.

If someone else wants to advocate the issue, please re-open it.

**Comment by thebigredgeek** [comment]
I'm happy to continue advocating integration of debug into `graphql-server` and `apollo-client`.  I don't agree that the output is non-parseable by any means.  The output is standardized and can be easily transformed using bash and a regex, or pretty much any other log uptake tool on the planet.  I'll find some time to put in a PR in the next few weeks.  Until then, shall we reopen the issue or open a duplicate @helfer @stubailo

**Comment by gajus** [comment]
> The output is standardized and can be easily transformed using bash and a regex, or pretty much any other log uptake tool on the planet.

```js
debug('parse\nthis\nfor\nme');
```

will produce output:

```
@applaudience:showtime-api:server parse
@applaudience:showtime-api:server this
@applaudience:showtime-api:server for
@applaudience:showtime-api:server me +0ms
```

which is useless for any time series logging.

**Comment by gajus** [comment]
Assuming the sole purpose is debugging at the time of development, "debug" is fine. If there is any use case of logging this, use [Bunyan](https://github.com/trentm/node-bunyan) or [Winston](https://github.com/winstonjs/winston).

**Comment by thebigredgeek** [comment]
That is lib abuse, and an admitted failure to parse out `\n` and other escape sequences from the namespace.  That isn't documented nor is it intended, fwiw

**Comment by gajus** [comment]
> That is lib abuse, and an admitted failure to parse out \n and other escape sequences from the namespace.

Might be worth documenting this. Not a word about it in the docs.

The same (non parsable) applies to any arguments passed to "debug":

```js
debug('foo', {me: 'not parsable either'})
```

produces:

```
@applaudience:showtime-api:server foo { me: 'not parsable either' } +0ms
```

Again, fine for debugging, useless for logging.

**Comment by thebigredgeek** [comment]
Well, the docs don't mention using escape sequences in the namespace either ;).  But we definitely need to add better sanitation.

I agree that if you have complex logging needs, debug might not be right for you.  That said, I think debug is a great solution in 80%+ of cases, and I think calling it "useless of logging" isn't really accurate at all.  I think it's enough for most people, and useful when embedded in libs like `graphql-server` and `apollo-client` because it improves DX and provides a means to see what is going on with a very small footprint.
