### ISSUE TITLE
Should suppress console.error "Error in formatError" when not in debug mode

### ISSUE THREAD

**Issue by christophercliff** [apollographql/graphql-server#344]
This appears to be inconsistent behavior but maybe I'm missing something. See line: https://github.com/apollographql/graphql-server/blob/e6f09c01bed12f8b3bb2b3c28383786b7c45dfe9/packages/graphql-server-core/src/runQuery.ts#L77

Reproduce: Start a server with `debug: false` option, throw an error in your `formatError` method.
Expected: No logging.
Actual: Logs the error.

**Comment by helfer** [comment]
@christophercliff While technically correct I don't think people should throw errors in their `formatError` function so it's probably not that big of an issue. However, I'd be happy to accept a PR to take into account the `debug` variable, if you would like to make one. While you're at it, you could also improve the error message in the subsequent error to something more informative than "Internal Server Error". Maybe "Internal Server Error: formatError function throws"

**Comment by helfer** [comment]
I think I'll close this since it's not really an issue in my opinion. Still happy to accept a PR to change the behavior or the docs.
