### ISSUE TITLE
update CHANGELOG.md?

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/graphql-server#352]
It looks like people are forgetting to update CHANGELOG.md?  This should probably be a required part of the release process:

```bash
git changelog # groom the log, use #pr and @contributor suffix for each line

git commit -am 'release x.y.z'

git push

git release create x.y.z

npm publish
```

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/blob/master/CHANGELOG.md

**Comment by helfer** [comment]
Thanks @thebigredgeek. If there's a specific thing missing in the changelog, please make a PR. For the general case there's already a PR template that includes "update the changelog".

**Comment by thebigredgeek** [comment]
https://github.com/apollographql/graphql-server/blob/master/CHANGELOG.md

Last documented change was 0.5.2, but 0.6.0 appears to be tagged and published.  I can't really speak to what needs to go into the CHANGELOG for 0.6.0.

**Comment by corydeppen** [comment]
Looks like it's still out of sync and missing releases 1.1.7, 1.2.0, and 1.3.0. Is it that things in VNEXT haven't been split out into sections for each release, or are there fixes/enhancements missing altogether from the changelog?
