### ISSUE TITLE
UI breaks with nginx reverse proxy

### ISSUE THREAD

**Issue by drFabio** [apollographql/graphql-server#355]
Using apollo-server 0.3.3 with an Nginx reverse proxy I get the following behaviour when I access the UI by the reverse proxy (direct access works fine, the reverse proxy is also working):
```html
"<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.11.13</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n"
```

I am using graphiql-express like the following:

```javascript
const { apolloExpress, graphiqlExpress } = require('apollo-server')
// ...
const app = express()

app.use(cors({origin: true, credentials: true}))
app.use('/graphql',
  bodyParser.json(),
  apolloExpress({
    schema,
    context: {}
  })
)
app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql'
}))
```
Is there anything on the graphiqlExpress configuration that  I need to pass for it to accept the proxy?

**Comment by DxCx** [comment]
sounds like the requests are forwared as GET and not POST.
anyway, apollo-server 0.3.3 is pretty old now, you should really upgrade to `graphql-server-express`

**Comment by drFabio** [comment]
Yeah I just realized that today . Will migrate and check it . Thanks for the response

**Comment by drFabio** [comment]
@DxCx  I updated, it is not a Method missdirection but maybe something else, anyway thanks for the input!
