### ISSUE TITLE
passHeader not in the header

### ISSUE THREAD

**Issue by comus** [apollographql/graphql-server#363]
see: 
https://github.com/apollographql/graphql-server/blob/d648c3efb83166e7834331c81b329b27c1364093/packages/graphql-server-module-graphiql/src/renderGraphiQL.ts

missing the usage of passHeader

i also commented here:
https://github.com/apollographql/graphql-server/commit/c4fabe367507f048f756ab4772942382449ef5a8#diff-590079b08b899b8986eea47e62859703L109

**Comment by helfer** [comment]
@comus looks like that was forgotten. Would you mind making a PR to add it back?

cc @Urigo

**Comment by Urigo** [comment]
@comus thanks, my bad...
