### ISSUE TITLE
passHeader not working anymore

### ISSUE THREAD

**Issue by jay1337** [apollographql/graphql-server#368]
Hello,

The `passHeader` option when calling `graphiqlExpress` now has no effect.
The option is no more used to calculate the result returned by `renderGraphiQL` function in `RenderGraphiQL.ts`.

Can you fix it ? (just re-adding the line with `${passHeader}` in `RenderGraphiQL.ts` as it was previously ...)

Thanks a lot.

**Comment by cesarsolorzano** [comment]
already fixed #364

**Comment by helfer** [comment]
@jay1337 you probably need to update your version of graphql-server.

**Comment by jay1337** [comment]
Thanks for your answers.

@helfer my installed version is up to date but the the fix has not yet been included in a new NPM package release...

**Comment by helfer** [comment]
@jay1337 what version are you running? Did I not release the latest changes? 🤔

**Comment by helfer** [comment]
nvm, looks like I didn't release. 0.7.2 is out now and should have the fix included.

**Comment by jay1337** [comment]
@helfer It works. Thanks a lot !
