### ISSUE TITLE
Missmatch with npmjs.com

### ISSUE THREAD

**Issue by Aides359** [apollographql/graphql-server#369]
The [npm link on graphql.org](http://graphql.org/code/#graphql-server-http-dev-apollodata-com-tools-graphql-server-index-html-github-https-github-com-apollostack-graphql-server-npm-https-www-npmjs-com-package-graphql-server) leads to the [graphql-server npm page](https://www.npmjs.com/package/graphql-server) which references [github.com/apollostack/apollo-server](https://github.com/apollostack/apollo-server) as repository which den forwards to [github.com/apollographql/graphql-server](https://github.com/apollographql/graphql-server).

The npm page further uses a readme that seems to be deprecated, saying that one should run `npm install apollo-server` to install and use some code syntax if I'm not mistaken.

This problem only became apparent when npm complained because of a peer dependency missmatch, leading to #291 and #243 explaining that this was deprecated and `npm install graphql-server-<variant>` was the correct syntax as also noted in the readme of this repository.

All in all the conflicting and deprecated information is really confusing when starting using this lib so I think the information should be updated accordingly.

**Comment by helfer** [comment]
Thanks for bringing this to our attention, I'm fixing it right now.

@DxCx it also looks like the README.md files on npm for each package are extremely minimal and just link to the docs. I think we should change that.

**Comment by DxCx** [comment]
@helfer 
each package in `packages` can contain it's own README.md,
if you will remember when we spoke about splitting to variants you said that you will update the READMEs after we split..

**Comment by helfer** [comment]
Haha, I don't remember that, but it sounds like something I would say. Since I don't have a lot of time right now, I hope we can split up the work among a few people. Do you remember who the main authors are for the various packages?

**Comment by DxCx** [comment]
nope, we can probably dig it from git log..
seems like:
`koa` - @HriBB 
`hapi` - @nnance 
`express` - @nnance 
lambda has a readme as far as i remember..

**Comment by helfer** [comment]
ok, I think none of these people have made any commits recently. Let's just create an issue and tag it with "help wanted"!

**Comment by helfer** [comment]
#373.
