### ISSUE TITLE
RFC: Modular and Simplistic GraphQL Backend API

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/graphql-server#371]
Right now, it requires a LOT of boilerplate to set up a GraphQL API.  You have to piecemeal a lot of different base components together in order to stand up a server, and I would guess that 80%+ of the time the servers do just about the same thing with the just about same constraints.  Having to deal with so much boilerplate creates a lot of adoption hurdles for teams wanting to give GraphQL a try, requiring a lot more design decisions and research in order to become productive.

I think it makes sense to figure out a way to optimize for that 80% rather than the "maybe this won't work for everyone" scenario.  We definitely want to keep the piecemeal approach as a viable option (graphql-server + graphql-tools + apollo-errors + etc etc), but I think a higher-lever server API would go a long way in promoting the adoption of GraphQL by otherwise hesitant developers by removing the fear of the unknown.

I presented a rough idea during the server group session at Apollo Day.  I've put together a simple gist, [here](https://gist.github.com/thebigredgeek/3e5d9757b054b642062569424f7fee03), of what I believe would be a very approachable and simple server API without the necessity of boilerplate code / boilerplate design decisions.

I'd love to get some community feedback on this, and get the ball rolling towards a project that could provide a gentler transition for developers who are curious about GraphQL.

**Comment by helfer** [comment]
Thanks @thebigredgeek! A bit of context would be nice. I don't think most people want to click on links before at least having some idea of what they'll find there.

**Comment by smolinari** [comment]
I get the gist of it (haha! pun intended!) and it is the start to a discussion that is definitely the next step after GraphQL. 

Why the name "Solaris" though? Project Solaris? Or should that be the name of the backend? If yes to the latter question, why not simply "Apollo Platform"? That sounds really cool to me. 😄 

Scott

**Comment by thebigredgeek** [comment]
IDK, just an idea for the project name.  Don't much care what it is called haha

**Comment by thebigredgeek** [comment]
@helfer let me know if the above explanation is verbose enough

**Comment by helfer** [comment]
Hey @thebigredgeek, let us know if you've built something in this direction. I think it could be interesting for people who want something like it.

**Comment by thebigredgeek** [comment]
I think we might be building and releasing this over here at Collective. We'd love your help @helfer and @stubailo !
