### ISSUE TITLE
Microservices using Apollo

### ISSUE THREAD

**Issue by rwatts3** [apollographql/graphql-server#383]
Greetings,

I am trying to decide the best way to build microservices using apollo. 
I recently came across this site.  https://www.graphqlhub.com/playground

If you attempt to write a query you'll notice the first thing you get is a list of services. 
hn, twitter, graphqlhub etc ...

Once you are nested within that service you can then write queries against that service.
I like how this keeps everything at one end point.

My question is how would one implement this with apollo ? 

Thank you in advance.

**Comment by helfer** [comment]
@rwatts3 that page simply uses [GraphiQL](https://github.com/graphql/graphiql) against the GraphQLHub schema, which contains all of those services. The schema was manually written to combine the services into one schema.

For learning about GraphQL in general, I can recommend graphql.org as a pretty good starting place.

**Comment by rwatts3** [comment]
Thank you.  

I probably should have  mentioned  that I'm aware that it's using graphiql. I suppose my question is more so if there is an example of how to combine the schema in such a way using Apollo ? Of there is no example could you give me a quick pointer and I'll take it from there.  

Thank you for your time.

**Comment by smolinari** [comment]
Have a look at [gRPC](http://www.grpc.io/). I think it is a better solution for microservice communication. 

Scott

**Comment by helfer** [comment]
@rwatts3 I think there's nothing magic about GraphqlHub, that entire schema was written by hand, and it just happens to combine everything into one schema at the root field. AFAICT there are no other connections between the services there.
