### ISSUE TITLE
TS2709: Cannot use namespace 'Cookies' as a type.

### ISSUE THREAD

**Issue by sarkistlt** [apollographql/graphql-server#385]
`ERROR in [at-loader] ./node_modules/@types/koa/index.d.ts:651:18 
    TS2709: Cannot use namespace 'Cookies' as a type.`

I don't now if I should post this issue in `koa` rep, but in my project koa is only dependency for apollo-server

**Comment by sarkistlt** [comment]
solved with using `graphql-server-express` instead of `apollo-server`

**Comment by patrickdevivo** [comment]
I'm encountering the same issue, I tried using `graphql-server-express` but had the same error
