### ISSUE TITLE
Error : TypeError: nodeAndDefs[responseName].push is not a function

### ISSUE THREAD

**Issue by FlyersWeb** [apollographql/graphql-server#387]
When I try to create a GraphQL server with a GraphQLObject having a constructor field I get the error `TypeError: nodeAndDefs[responseName].push is not a function`

## Intended outcome
Server should not throw error

## Actual outcome
`TypeError: nodeAndDefs[responseName].push is not a function`

## How to reproduce
Create a GraphQL object with a constructor field
```
    new GraphQLObjectType({
        name : 'FooType',
        fields : {
            ['constructor'] : {
                type : new GraphQLNonNull(GraphQLString)
            },
        }
    })
```

Let me know if you need more insights

**Comment by FlyersWeb** [comment]
The query associated :

```
query dummyQuery {
      ...subscriptionInfo
      __typename
}
fragment subscriptionInfo on SubscriptionType {
  constructor
  __typename
}
```

**Comment by helfer** [comment]
@FlyersWeb I suspect this may be something in graphql-js. Can you check if you get the same error if you execute the query directly against the `graphql` function from `graphql-js`?

**Comment by FlyersWeb** [comment]
Corrected by https://github.com/graphql/graphql-js/pull/864

**Comment by FlyersWeb** [comment]
I'm waiting for graphqljs new release and apollo server new release to resolve issue

**Comment by helfer** [comment]
I think this is fixed now.
