### ISSUE TITLE
shared interface resolver

### ISSUE THREAD

**Issue by thomasMary** [apollographql/graphql-server#388]
Is it possible to create resolvers for an interface such as:
```
interface Vehicle {
  maxSpeed(unit: string): Int
}
type Airplane implements Vehicle {
  maxSpeed(unit: string): Int
  wingspan: Int
}
type Car implements Vehicle {
  maxSpeed(unit: string): Int
  licensePlate: String
}
```
```
const resolverMap = {
  Vehicle: {
     maxSpeed: ({ maxSpeed }, { unit }) => speedToUnit(maxSpeed, unit),
  },
};
```
So I don't have to duplicate the logic?
Thanks

**Comment by helfer** [comment]
@thomasMary no, that's not possible at the moment. Resolvers always have to be defined on the implementing type.

PS: This question would technically belong on the graphql-tools repo.
