### ISSUE TITLE
Document for security

### ISSUE THREAD

**Issue by lednhatkhanh** [apollographql/graphql-server#392]
Hello, I'm trying to create an Apollo server and finding for security tips like rate limiting, protection against DDOS attack... But I could not find it anywhere in the docs, any plans on wrting these docs or are there any useful article that people like me cantake a look at, thank you.

**Comment by helfer** [comment]
Hi @lednhatkhanh we don't currently have any good docs on rate limiting & co. If you have some thoughts on it, it would be great to write them down and share them with the community, as best practices are still emerging. 🙂
