### ISSUE TITLE
The best way to design Schema

### ISSUE THREAD

**Issue by MGazi42** [apollographql/graphql-server#393]
I am new in graphql. I don't know how can I design schema the best way. I also thinking how can I define multiple schema ? Like the below;

`const executableSchema = makeExecutableSchema({
  typeDefs: [Schema1,Schema2]
  resolvers: [Resolvers1,Resolvers2]
});`

Because we have project might grow up. We can not go on like this;

`const Schema = `
    type Author {
        id: String
        name: String
        image: String
        books: [Book]
    }
    type Book {
        id: String
        title: String
        image: String
        authorId: String
        description: String
        author: Author
    }
    input BookInput {
        id: String
        title: String
        image: String
        description: String
        authorId: String
    }
    type QueryRoot {
        authors: [Author]
        books: [Book]
        bookById(id: String!): Book
        bookSearch(keyword: String!): Book
        secret: String
    }
    type MutationRoot {
        addBook(book: BookInput!): Book
    }
    schema {
        query: QueryRoot
        mutation: MutationRoot
    }
`;
`

When I research on Github to graphql starter kit, I was find [https://github.com/w3tecch/express-graphql-typescript-boilerplate](url) this repo and I think this repo is awesome. Why do I think so? Because Schema design in this repo is really super. Let's take a look the Schema design;

`
import { GraphQLObjectType, GraphQLSchema } from 'graphql';

import { GraphQLErrorHandling } from '../core';
import {
    FindAllAuthorsQuery,
    FindAuthorByIdQuery,
    FindAllBooksQuery,
    FindBookByIdQuery,
    SearchQuery
} from './queries';
import {
    CreateAuthorMutation,
    DeleteAuthorMutation,
    UpdateAuthorMutation
} from './mutations';

export class Schema {

    private static instance: Schema;

    private rootQuery: GraphQLObjectType = new GraphQLObjectType({
        name: 'Query',
        fields: {
            search: new SearchQuery(),
            findAllAuthors: new FindAllAuthorsQuery(),
            findAuthorById: new FindAuthorByIdQuery(),
            findAllBooks: new FindAllBooksQuery(),
            findBookById: new FindBookByIdQuery()
        }
    });

    private rootMutation: GraphQLObjectType = new GraphQLObjectType({
        name: 'Mutation',
        fields: {
            createAuthor: new CreateAuthorMutation(),
            updateAuthor: new UpdateAuthorMutation(),
            deleteAuthor: new DeleteAuthorMutation()
        }
    });

    private schema: GraphQLSchema = new GraphQLSchema({
        query: this.rootQuery,
        mutation: this.rootMutation
    });

    static get(): GraphQLSchema {
        if (!Schema.instance) {
            Schema.instance = new Schema();
            GraphQLErrorHandling.watch(Schema.instance.schema);
        }
        return Schema.instance.schema;
    }
}

`
But unfortunately, in this repo was used express-graphql and I'm disappointed. Although using typescript. My question is how can I schema design like the above ? 

I'm sorry for my bad english.

**Comment by mairh** [comment]
@MGazi42 Usually, these type of questions should be asked on stackoverflow. Nonetheless just to get you started you can have a look at https://github.com/sysgears/apollo-fullstack-starter-kit which divides the schema in a really nice way using `graphql-server-express`

**Comment by MGazi42** [comment]
I was look at the repo you suggested. But it looks like it is not a very nice way. As you say, I asked on stackoverflow [http://stackoverflow.com/questions/44034804/the-best-way-to-design-schema](url)

**Comment by otonielguajardo** [comment]
I know this thread is closed but I was wundering the same thing, because I noticed in some repos the schema was designed using graphql language, and in others, using javascript. So this article pointed me in the right direction https://blog.apollographql.com/three-ways-to-represent-your-graphql-schema-a41f4175100d
