### ISSUE TITLE
Issue with GraphQL query

### ISSUE THREAD

**Issue by jamsheer-thottathil** [apollographql/graphql-server#395]
I am working with Apollo GraphQL .

I have table with three  records and queried from the same with graphQL as flows 

Query 

```
query getAuthors($lastName: String){
  author(lastName:$lastName){
    id
    firstName
    lastName
  }
}
```

Query variable

```
{
  "lastName": "Smith"
}

```

Result

```
{
  "data": {
    "author": [
      {
        "id": 1,
        "firstName": "James",
        "lastName": "Smith"
      }
    ]
  }
}
```

But if I  supply query variable as null, I am getting the  response as follows (Seems like fetching all records )

Query variable

```
{
  "lastName": null
}

```
Result 

```
{
  "data": {
    "author": [ {
        "id": 1,
        "firstName": "James",
        "lastName": "Smith"
      },
      {
        "id": 2,
        "firstName": "Maria",
        "lastName": "Garcia"
      },
      {
        "id": 3,
        "firstName": "Maria",
        "lastName": "Rodriguez"
      }]
  }
}
```

I am confusing that why i am getting all records even if I pass null value for lastName

**Comment by DxCx** [comment]
hey @jamsheer-thottathil 
can you also paste code of your resolver?
this is what your resolver returns..
also, what would you expect to if variable is null?

**Comment by jamsheer-thottathil** [comment]
I want to return only records which has lastName is null.

My resolver is

https://github.com/apollographql/graphql-server/issues/395#issuecomment-302409483

const resolvers = {
  Query: {
    author(_, args) {
      return Author.findAll({ where: args });
    },

**Comment by DxCx** [comment]
hmm, to me it sounds like findAll with lastName: null just find all lastNames..
can you test it off-graphql? i mean like open small js file and console.log the result of Author.findall(where last name is null)

**Comment by jamsheer-thottathil** [comment]
Right,  findAll with lastName: null just find all lastNames .
In my case its making sense less. If give null value for lastName (currently handling with client side validation )Its leads to return all records , It may give wrong search result for end user.

**Comment by DxCx** [comment]
alright, looks like this is resolved =)
you just need to send the right query to your database..
