### ISSUE TITLE
add support for fastify

### ISSUE THREAD

**Issue by phra** [apollographql/graphql-server#402]
hi,

it would be nice to have also official support for [fastify](https://github.com/fastify/fastify).

are you considering it?

**Comment by helfer** [comment]
Hi @phra I'd be happy to merge a PR that adds support for fastify :wink:

**Comment by phra** [comment]
here it is: #421

**Comment by helfer** [comment]
Hey, really sorry for the about-face, but after discussing with the team we think that the extra maintenance burden is not justifiable at this moment. I'd like to make it up to you though, so if you DM me on Twitter or on the Apollo Slack I'll make sure we send you some Apollo swag! :heart:

**Comment by coopnd** [comment]
Hi!  I love Apollo and am falling in love with fastify and was sad to see this wouldn't be supported in the near future.  I tried out an implementation as a plugin, so if anyone has an interest in using these things together, [by all means do](https://github.com/coopnd/fastify-apollo).  Hope you guy's are happy with it!

**Comment by phra** [comment]
@coopnd big up! 🎉 i didn't have time in these weeks to work on the plugin.
