### ISSUE TITLE
Issues upgrading to graphql 0.10.0

### ISSUE THREAD

**Issue by joncursi** [apollographql/graphql-server#404]
I upgraded to graphQL 0.10.0 and my clients stopped being able to communicate with my graphQL server (using express in Meteor). There is a silent failure, somewhere, and I can't track it down. There are two breaking changes in 0.10.0 that my app isn't infringing upon as far as I can tell:

```
Spec compliance: forbid duplicate type definitions
Spec compliance: disallow inappropriate coercion of non-Int values to Int
```

Anyone else getting this?

**Comment by strues** [comment]
I got a couple errors and decided to hold off until Apollo releases an update.

**Comment by helfer** [comment]
Thanks for filing an issue @joncursi. #407 should take care of this. I will release a new version shortly.
