### ISSUE TITLE
Update reference to GraphIQL 0.9.1 to newer version?

### ISSUE THREAD

**Issue by alankent** [apollographql/graphql-server#405]
In https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-module-graphiql/src/renderGraphiQL.ts#L32 there is a hard coded reference to 0.9.1. I am having troubles with this version which look the same as https://github.com/graphql/graphiql/issues/356. Is there any reason not to upgrade to a newer version?

(I am trying to get GraphIQL to fetch the schema from a PHP GraphQL server, so I fetch the schema remotely, build it into a local schema object, but then get an error message that looks like 356 above. It mentioned the bug was fixed in 0.9.2.)

**Comment by helfer** [comment]
Thanks for filing an issue @alankent. #407 should take care of this. I will release a new version shortly.
