### ISSUE TITLE
Type defined more than once error

### ISSUE THREAD

**Issue by pho3nixf1re** [apollographql/graphql-server#411]
After upgrading graphql to 0.10.1 I now see the error `Error: Type "MyType" defined more than once` when compiling my schema. This did not happen before the upgrade. This appears to only affect enum types. My schema is organized where each type definition imports the types it depends on. Example:

```js
import DistanceUnit from '../enums/distance-unit';
import GameType from '../enums/game-type';

const Run = `
  type Run {
    source: GameType
    distance: Float
    distanceUnit: DistanceUnit
  }
`;

export const schema = () => [Run, DistanceUnit, GameType];

export const resolvers = {
  Run: {}
};
```

Notice that the enums are exported with the schema string. The `GameType` enum is used by several types and so it is include in multiple places.

**Note** that this error **does not** happen if you duplicate the type at the same level. See how https://launchpad.graphql.com/qpm7w4znp (working) compares with https://launchpad.graphql.com/w05jlvv5z (not working).

## Intended outcome

When compiling the schema each included enum type is only defined once regardless of how many times it is included thus preventing the new uniqueness check for types in the reference implementation.

## Actual outcome

An error is thrown when including an enum type more than once.

## Reproduction

https://launchpad.graphql.com/w05jlvv5z

**Comment by helfer** [comment]
Hi @pho3nixf1re, I think this doesn't have anything to do with graphql-server, but it could be a bug in graphql-tools. Please open the issue on the graphql-tools repository. Thanks!
