### ISSUE TITLE
Feature request: Expose graphiql so it can be customized i.e. add company logo etc

### ISSUE THREAD

**Issue by emmanuelbuah** [apollographql/graphql-server#412]
The stock graphiql app is a good base/starting point but doesn't offer extension or customization. Developers/Teams might need to add Company Logo, Http Headers, ability to changing the graphql url etc. Graphiql was designed with customization in mind via the graphiql children components but the current implementation in Apollo abstracts way that customization.  It would be beneficiary to the community if graphiql in Apollo was exposed in a way that doesn't take away benefits naturally provided by the graphiql application.

**Comment by helfer** [comment]
Hi @emmanuelbuah, that's a great idea, but I think if you want to customize GraphiQL, you can use the actual original repo and just expose that on another endpoint yourself. I think that's probably the most general option, and it doesn't require any action on our part.

I'd be happy to reconsider if more people have a need to configure a specific thing.
