### ISSUE TITLE
Context vs RootValue

### ISSUE THREAD

**Issue by servermeta** [apollographql/graphql-server#413]
In graphqloptions, what is the difference between context and rootvalue? 

When should I use one, and when should I use the other?

At the moment I'm attaching connectors and other sensitive data to the context, is this safe? Can the user read the context or the rootvalue of his queries?

**Comment by stubailo** [comment]
Nope! the user can only read the fields you expose in the API, they can't see the context or rootValue directly.

Back in the day, `context` didn't exist, so `rootValue` was used for this stuff. These days, I think context is pretty much always the right thing to use.

Perhaps you could send a PR to the docs making this clearer!
