### ISSUE TITLE
Error - "Must provide document"

### ISSUE THREAD

**Issue by Siyfion** [apollographql/graphql-server#415]
I'm having huge issues with sending large amounts of data to an Apollo mutation, as detailed here: https://github.com/apollographql/apollo-client/issues/1696 - I originally thought it was an apollo client issue.

After looking through the recommendations made in: https://github.com/apollographql/apollo-client/issues/1233

I tried implementing various additional CORS options, each with no success. Any idea's or pointers would be great.

**Comment by helfer** [comment]
Have you tried logging the full request on the server before passing it into the GraphQL part, just to see if everything is there? It could be that the request is somehow truncated because of the size, and thus no valid body is present, which would lead to the error message above.

**Comment by helfer** [comment]
Closing this, but feel free to keep discussing here if you still have this issue.
