### ISSUE TITLE
graphiqlOptions should support being called as a function that is passed the request

### ISSUE THREAD

**Issue by NeoPhi** [apollographql/graphql-server#418]
We have a need to dynamically determine the `graphiqlOptions` that should be used on a per request. This would mirror the semantics of `graphqlOptions` supporting a function.

This approach could also be used to address https://github.com/apollographql/graphql-server/issues/399 by examining the incoming Host header to dynamically generate the `subscriptionsEndpoint` and/or `endpointURL`.

**Comment by helfer** [comment]
@NeoPhi I think that's a great idea. Do you have time to make a PR that would allow both an object and a function as `graphiqlOptions`? 🙂
