### ISSUE TITLE
Error: Must provide document

### ISSUE THREAD

**Issue by 39Er** [apollographql/graphql-server#432]
I want to use application/graphql requests,but I get this error.
In my code ,I have these related:

```
app.use(bodyParser.text({ type: 'application/graphql' }));
app.use('/graphql', graphqlExpress((req) => {
  if (req.is('application/graphql')) {
    req.body = { query: req.body };
  }
  return {
      schema,
    };
}));
```
I think these are same as the Readme,but it doesn't work.
What's the problem?

**Comment by helfer** [comment]
Hey @39Er, I think this is related to #379, let's track it there.
